export const fallbackCategories = [
  { id: 1, name: "Патологоанатомические вскрытия", slug: "vskrytiya", description: "Вскрытие трупов с целью установления причины смерти", icon: "Activity", sortOrder: 1, isActive: true, createdAt: new Date(), updatedAt: new Date() },
  { id: 2, name: "Гистологические исследования", slug: "gistologiya", description: "Микроскопическое исследование тканей для диагностики заболеваний", icon: "Microscope", sortOrder: 2, isActive: true, createdAt: new Date(), updatedAt: new Date() },
  { id: 3, name: "Цитологические исследования", slug: "tsitologiya", description: "Исследование отдельных клеток для выявления патологий", icon: "Search", sortOrder: 3, isActive: true, createdAt: new Date(), updatedAt: new Date() },
  { id: 4, name: "Судебно-медицинская экспертиза", slug: "sudebnaya-ekspertiza", description: "Экспертные исследования для органов дознания и суда", icon: "FileText", sortOrder: 4, isActive: true, createdAt: new Date(), updatedAt: new Date() },
  { id: 5, name: "Морфологическая диагностика", slug: "morfologicheskaya-diagnostika", description: "Комплексная диагностика на основе морфологических исследований", icon: "Stethoscope", sortOrder: 5, isActive: true, createdAt: new Date(), updatedAt: new Date() },
  { id: 6, name: "Иммуногистохимические исследования", slug: "immunogistokhimiya", description: "Выявление специфических антигенов в тканях", icon: "FlaskConical", sortOrder: 6, isActive: true, createdAt: new Date(), updatedAt: new Date() },
];

export const fallbackServices = [
  { id: 1, categoryId: 1, name: "Судебно-медицинское вскрытие", slug: "sudebno-medicinskoe-vskrytie", shortDescription: "Вскрытие трупа по решению следственных органов", description: "Полное патологоанатомическое вскрытие с целью установления причины смерти в рамках уголовного или гражданского дела. Включает макроскопическое и микроскопическое исследование.", price: "по запросу", duration: "3-5 рабочих дней", requirements: "Направление из следственных органов, документы удостоверяющие личность", isActive: true, sortOrder: 1, createdAt: new Date(), updatedAt: new Date() },
  { id: 2, categoryId: 1, name: "Клинико-патологическое вскрытие", slug: "kliniko-patologicheskoe-vskrytie", shortDescription: "Вскрытие для выяснения клинического диагноза", description: "Вскрытие трупа с целью проверки клинического диагноза, оценки эффективности проведённого лечения и выявления нозологических форм заболеваний.", price: "по запросу", duration: "5-7 рабочих дней", requirements: "Направление из лечебного учреждения, выписка из медицинской карты", isActive: true, sortOrder: 2, createdAt: new Date(), updatedAt: new Date() },
  { id: 3, categoryId: 1, name: "Патологоанатомическое вскрытие новорождённых", slug: "vskrytie-novorozhdennykh", shortDescription: "Специализированное вскрытие плодов и новорождённых", description: "Вскрытие мёртворождённых плодов, новорождённых и детей раннего возраста с целью установления причины смерти и патологии развития.", price: "по запросу", duration: "7-10 рабочих дней", requirements: "Направление из роддома или детской больницы", isActive: true, sortOrder: 3, createdAt: new Date(), updatedAt: new Date() },
  { id: 4, categoryId: 2, name: "Гистологическое исследование биоптата", slug: "gistologiya-bioptat", shortDescription: "Исследование образцов тканей, полученных при биопсии", description: "Микроскопическое исследование тканей, полученных при биопсии, операции или аутопсии. Включает окраску гематоксилином-эозином и при необходимости специальные окраски.", price: "от 1 500 руб.", duration: "3-5 рабочих дней", requirements: "Направление от лечащего врача, материал в 10% формалине", isActive: true, sortOrder: 1, createdAt: new Date(), updatedAt: new Date() },
  { id: 5, categoryId: 2, name: "Экспресс-гистологическое исследование", slug: "ekspress-gistologiya", shortDescription: "Быстрое гистологическое исследование во время операции", description: "Внутриоперационное гистологическое исследование методом замораживания. Результат готов в течение 15-20 минут.", price: "от 3 000 руб.", duration: "15-20 минут", requirements: "Предварительная договорённость, материал свежий", isActive: true, sortOrder: 2, createdAt: new Date(), updatedAt: new Date() },
  { id: 6, categoryId: 2, name: "Специальные гистохимические окраски", slug: "gistokhimicheskie-okraski", shortDescription: "Дополнительные окраски для уточнения диагноза", description: "Применение специальных методик окрашивания (PAS, трихромные окраски, сильверимпрегнация и др.) для выявления специфических структур и веществ в тканях.", price: "от 800 руб.", duration: "1-2 рабочих дня", requirements: "Направление от лечащего врача", isActive: true, sortOrder: 3, createdAt: new Date(), updatedAt: new Date() },
  { id: 7, categoryId: 3, name: "Цитологическое исследование мазка", slug: "tsitologiya-mazok", shortDescription: "Исследование клеточного состава мазка", description: "Микроскопическое исследование мазков с различных поверхностей и органов (шейка матки, бронхи, щитовидная железа и др.) для выявления атипичных клеток.", price: "от 900 руб.", duration: "2-3 рабочих дня", requirements: "Направление от лечащего врача", isActive: true, sortOrder: 1, createdAt: new Date(), updatedAt: new Date() },
  { id: 8, categoryId: 3, name: "Тонкоигольная аспирационная биопсия (ТАБ)", slug: "tonkoigolnaya-biopsiya", shortDescription: "Пункционная биопсия под контролем УЗИ", description: "Получение материала для цитологического исследования путём пункции образования тонкой иглой под контролем ультразвукового исследования.", price: "от 2 000 руб.", duration: "2-3 рабочих дня", requirements: "Направление от лечащего врача, УЗИ заключение", isActive: true, sortOrder: 2, createdAt: new Date(), updatedAt: new Date() },
  { id: 9, categoryId: 4, name: "Судебно-медицинская экспертиза трупа", slug: "ekspertiza-trupa", shortDescription: "Комплексная экспертиза для следственных органов", description: "Полная судебно-медицинская экспертиза трупа, включающая макроскопическое и микроскопическое исследование, токсикологический анализ и составление экспертного заключения.", price: "по запросу", duration: "10-15 рабочих дней", requirements: "Постановление следователя или определение суда", isActive: true, sortOrder: 1, createdAt: new Date(), updatedAt: new Date() },
  { id: 10, categoryId: 4, name: "Судебно-медицинская экспертиза живого лица", slug: "ekspertiza-zhivogo-litsa", shortDescription: "Освидетельствование живых лиц", description: "Судебно-медицинское освидетельствование живых лиц с целью определения характера, давности и механизма образования повреждений, степени тяжести вреда здоровью.", price: "по запросу", duration: "5-7 рабочих дней", requirements: "Постановление следователя", isActive: true, sortOrder: 2, createdAt: new Date(), updatedAt: new Date() },
  { id: 11, categoryId: 5, name: "Комплексная морфологическая диагностика опухоли", slug: "kompleksnaya-diagnostika-ukholi", shortDescription: "Полная диагностика новообразований", description: "Комплексное исследование опухоли, включающее гистологическое, цитологическое и иммуногистохимическое исследования.", price: "от 5 000 руб.", duration: "7-10 рабочих дней", requirements: "Направление от онколога, биоптат или операционный материал", isActive: true, sortOrder: 1, createdAt: new Date(), updatedAt: new Date() },
  { id: 12, categoryId: 5, name: "Морфологическая верификация диагноза", slug: "verifikatsiya-diagnosta", shortDescription: "Подтверждение или уточнение клинического диагноза", description: "Пересмотр морфологических препаратов, полученных в других учреждениях, с целью верификации или уточнения диагноза (second opinion).", price: "от 3 500 руб.", duration: "5-7 рабочих дней", requirements: "Стёкла с препаратами, заключение другого учреждения", isActive: true, sortOrder: 2, createdAt: new Date(), updatedAt: new Date() },
  { id: 13, categoryId: 6, name: "Иммуногистохимическое исследование (ИГХ)", slug: "immunogistokhimiya-ikh", shortDescription: "Выявление маркеров в тканях", description: "Иммуногистохимическое исследование с использованием панелей антител для уточнения гистогенеза опухоли, определения прогностических и предиктивных маркеров.", price: "от 2 500 руб.", duration: "3-5 рабочих дней", requirements: "Направление от онколога, гистологические препараты", isActive: true, sortOrder: 1, createdAt: new Date(), updatedAt: new Date() },
  { id: 14, categoryId: 6, name: "Флуоресцентная гибридизация in situ (FISH)", slug: "fish-analiz", shortDescription: "Молекулярно-генетический анализ клеток", description: "Метод молекулярной цитогенетики для выявления хромосомных аберраций, генных амплификаций и транслокаций в клетках опухоли.", price: "по запросу", duration: "7-14 рабочих дней", requirements: "Направление от онколога, парафиновый блок", isActive: true, sortOrder: 2, createdAt: new Date(), updatedAt: new Date() },
];

export const fallbackSettings: Record<string, string> = {
  orgName: "ГБУЗ \"РОД\"",
  orgFullName: "ГБУЗ \"Республиканский онкологический диспансер\"",
  address: "РСО-Алания, г. Владикавказ, ул. Титова, д. 1",
  phone: "+7 (8672) 55-55-55",
  email: "info@rod-ru.ru",
  workHours: "Пн-Пт: 8:00-17:00, Сб: 9:00-14:00",
  latitude: "43.0367",
  longitude: "44.6678",
};
